spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

  liquibase:
    change-log: ${LIQUIBASE_CHANGELOG}
    enabled: ${LIQUIBASE_ENABLED}

server:
  port: ${PORT:8080}