SPRING_APPLICATION_NAME=ms-account-reservation
PORT=8082

DB_URL=jdbc:postgresql://localhost:5432/account_reservation
DB_USERNAME=postgres
DB_PASSWORD=1111

JPA_DDL_AUTO=validate

LIQUIBASE_CHANGELOG=classpath:db/changelog/db.changelog-master.yaml
LIQUIBASE_ENABLED=true

MANAGEMENT_PORT=8083
MANAGEMENT_ENDPOINTS_INCLUDE=health,info,threaddump
SHUTDOWN_ACCESS=none

CURRENCY_CLIENT_API_KEY=ae237bae17706c37ebb8ba22
CURRENCY_CLIENT_BASE_URL=https://v6.exchangerate-api.com/v6
CURRENCY_CLIENT_CONNECT_TIMEOUT=5000
CURRENCY_CLIENT_READ_TIMEOUT=5000
CURRENCY_CLIENT_RETRY_ATTEMPTS=3
CURRENCY_CLIENT_RETRY_DELAY=1000
CURRENCY_CLIENT_RETRY_MULTIPLIER=2

REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_TIMEOUT=5000
HEALTH_INDICATOR_ENABLED=true

APP_ASYNC_CORE_POOL_SIZE=5
APP_ASYNC_MAX_POOL_SIZE=10
APP_ASYNC_QUEUE_CAPACITY=100
APP_ASYNC_THREAD_NAME_PREFIX=async-
APP_ASYNC_TIMEOUT_SECONDS=5

LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER=TRACE

CLIENT_EVENTS_KAFKA_BOOTSTRAP_SERVERS=localhost:9092
CLIENT_EVENTS_KAFKA_TOPIC_NAME=client-events
CLIENT_EVENTS_KAFKA_PRODUCER_ENABLED=true
CLIENT_EVENTS_KAFKA_PRODUCER_ACKS=all
CLIENT_EVENTS_KAFKA_PRODUCER_RETRIES=3
CLIENT_EVENTS_KAFKA_CONSUMER_ENABLED=true
CLIENT_EVENTS_KAFKA_CONSUMER_GROUP=client-events-group
CLIENT_EVENTS_KAFKA_CONSUMER_MAX_POLL_RECORDS=500
CLIENT_EVENTS_KAFKA_CONSUMER_AUTO_OFFSET_RESET=earliest
CLIENT_EVENTS_KAFKA_CONSUMER_ENABLE_AUTO_COMMIT=false
CLIENT_EVENTS_KAFKA_LISTENER_CONCURRENCY=3